# Development configuration overrides
# Use with: bundle exec jekyll serve --config _config.yml,_config_dev.yml

# Disable analytics in development
analytics:
  google:
    id: # disabled in dev
  goatcounter:
    id: # disabled in dev

# Enable incremental builds for faster development
incremental: true

# Show drafts and future posts
show_drafts: true
future: true

# Disable disk caching for live changes
disable_disk_cache: true

# Enable full error messages
strict_front_matter: true

# Livereload port (useful for development)
livereload_port: 35729

# Allow unsafe redirects for local development  
safe: false

# Enable detailed logging
verbose: true

# Development CDN (empty to use local files)
cdn: ""

# Disable PWA in development
pwa:
  enabled: false
  cache:
    enabled: false 