# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# polyglot configuration
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true

# Disable service worker to don't cache pages
service_worker: false

sass:
  sourcemap: never

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Madrid

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Playing AWS # the main title

# tagline: # it will display as the sub-title
#   en: Learn, remove barriers and practice
#   es: Aprende, elimina barreras y practica

# description: # used by seo meta and the atom feed
#   en: My personal blog related with AWS.
#   es: My blog personal para compartir cosas relacionadas con AWS.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://playingaws.com"

github:
  username: alazaroc # change to your github username

# twitter:
#   username: twitter_username # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Alejandro Lazaro Chueca
  # email: me@gmail.com
  links:
    # The first element serves as the copyright owner's link
    #- https://twitter.com/username      # change to your twitter homepage
    - https://github.com/alazaroc
    - https://www.linkedin.com/in/alejandro-lazaro-chueca/

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

analytics:
  google:
    id: G-HW1NDPDLBF # fill in your Google Analytics ID
  goatcounter:
    id: playingaws # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: goatcounter # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/favicons/favicon.ico

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: giscus  # [disqus | utterances | giscus]
  #   # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: alazaroc/blog-web-code
    repo_id: R_kgDOHA-hqQ
    category: Announcements
    category_id: DIC_kwDOHA-hqc4CT2E5
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: top # optional, default to 'bottom'
    lang: # optional, default to the value of `site.active_lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
# assets:
#   self_host:
#     enabled: # boolean, keep empty means false
#     # specify the Jekyll environment, empty means both
#     # only works if `assets.self_host.enabled` is 'true'
#     env: # [development|production]

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 20

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: true
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  # - "*.gem"
  # - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      last_modified_at:
      lang: en  
      lang-exclusive: ['en', 'es']
      description:
      category:
      tags:
      published: true
      level:
      pin: false
      featured_post: false
      comments: true
      sitemap: true
      media_subpath:
      image:
        path:
        header_post: false
    posts:
      last_modified_at:
      lang: en  
      lang-exclusive: ['en', 'es']
      description:
      category:
      tags:
      published: true
      level:
      pin: false
      featured_post: false
      comments: true
      sitemap: true
      media_subpath:
      image:
        path:
        header_post: false
