name: "Validation of the website"

on:
  push:
    branches:
      - main
      - "feature/*"
    paths-ignore:
      - .gitignore
      - README.md
      - CHANGELOG.md

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts' lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Dependencies
        run: |
          bundle install

      - name: Build and Test Site
        run: |
          # Environment variables
          SITE_DIR="_site"
          CONFIG_FILE="_config.yml"
          
          # Extracting baseurl without issues from the config file
          BASEURL=$(grep '^baseurl:' $CONFIG_FILE | sed 's/.*: *//;s/[\"'\'']//g;s/#.*//')

          # Initialize
          if [[ -z ${GITHUB_ACTION+x} ]]; then
            echo "ERROR: It is not allowed to deploy outside of the GitHub Action environment."
            exit 1
          fi

          # Build the site
          if [[ -d $SITE_DIR ]]; then
            rm -rf "$SITE_DIR"
          fi
          JEKYLL_ENV=production bundle exec jekyll build -d "$SITE_DIR$BASEURL" --config "$CONFIG_FILE"

          # Test the site with htmlproofer
          bundle exec htmlproofer --disable-external --allow-hash-href "$SITE_DIR"
